DISTNAME		=	sysreport-${V}
V				=	0.2.4
COMMENT			=	creates system health reports.
CATEGORIES		=	sysutils

MAINTAINER		=	Michael Wilson <mw@1wilson.org>
HOMEPAGE 		=	https://github.com/torarg/sysreport

# BSD
PERMIT_PACKAGE	=	Yes

SITES			=	https://github.com/torarg/sysreport/archive/refs/tags/
DISTFILES		=	sysreport-{}${V}${EXTRACT_SUFX}

.include <bsd.port.mk>
